# Generated by Django 5.2.3 on 2025-08-20 15:17

import datetime
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_voting', models.BooleanField(default=False)),
                ('entrepreneur_chance', models.FloatField(default=0.3)),
                ('election_interval', models.DurationField(default=datetime.timedelta(seconds=5400))),
                ('election_duration', models.DurationField(default=datetime.timedelta(seconds=30))),
                ('last_election_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('voting_started_at', models.DateTimeField(blank=True, null=True)),
                ('voting_paused_at', models.DateTimeField(blank=True, null=True)),
                ('voting_total_paused_seconds', models.IntegerField(default=0)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('total_paused_seconds', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(1, 'Безработный'), (2, 'Работник'), (3, 'Предприниматель')], default=1)),
                ('special_role', models.IntegerField(choices=[(1, 'Безработный'), (2, 'Работник'), (3, 'Предприниматель')], default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('money', models.IntegerField(default=10000)),
                ('influence', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_observer', models.BooleanField(default=False)),
            ],
        ),
    ]
