# Generated by Django 5.2.3 on 2025-07-04 14:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('creator', 'is_active')},
        ),
    ]
