# Generated by Django 5.2.3 on 2025-08-24 03:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_gameplayer_special_role_votesession_voteoption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AskedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered', models.BooleanField(default=False)),
                ('answer_choice', models.IntegerField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('asked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_asked', to='games.gameplayer')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asked_questions', to='games.game')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_received', to='games.gameplayer')),
            ],
        ),
        migrations.DeleteModel(
            name='ElectionVote',
        ),
        migrations.AddIndex(
            model_name='askedquestion',
            index=models.Index(fields=['game', 'answered'], name='games_asked_game_id_1d8de7_idx'),
        ),
        migrations.AddIndex(
            model_name='askedquestion',
            index=models.Index(fields=['target', 'answered'], name='games_asked_target__a7ff3e_idx'),
        ),
        migrations.AddIndex(
            model_name='askedquestion',
            index=models.Index(fields=['asked_by', 'created_at'], name='games_asked_asked_b_a75410_idx'),
        ),
    ]
