# Generated by Django 5.2.3 on 2025-07-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_game_unique_together_game_paused_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='entrepreneur_chance',
            field=models.FloatField(default=0.3),
        ),
    ]
