# Generated by Django 5.2.3 on 2025-07-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_playerprofile_entrepreneur_chance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprofile',
            name='influence',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='money',
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='influence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='money',
            field=models.IntegerField(default=10000),
        ),
    ]
