# Generated by Django 5.2.3 on 2025-07-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_remove_playerprofile_influence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprofile',
            name='entrepreneur_chance',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='role',
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='entrepreneur_chance',
            field=models.FloatField(default=0.3),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='role',
            field=models.IntegerField(choices=[(0, 'Наблюдатель'), (1, 'Безработный'), (2, 'Работник'), (3, 'Предприниматель'), (4, 'Банкир'), (5, 'Государственный деятель')], default=0),
        ),
    ]
